CREATE TABLE StreamerStats (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Date DATETIME NOT NULL,
    AdBreaksMinutes INT,
    AdTimeSecondsPerHour INT,
    MinutesStreamed INT,
    SubRevenue DECIMAL(18,2),
    PrimeRevenue DECIMAL(18,2),
    GiftedSubsRevenue DECIMAL(18,2),
    MultiMonthGiftedSubsRevenue DECIMAL(18,2),
    BitsRevenue DECIMAL(18,2),
    AdRevenue DECIMAL(18,2),
    TurboRevenue DECIMAL(18,2),
    GameSalesRevenue DECIMAL(18,2),
    ExtensionsRevenue DECIMAL(18,2),
    BountiesRevenue DECIMAL(18,2),
    OtherBitsInteractionsRevenue DECIMAL(18,2),
    HypeChatRevenue DECIMAL(18,2),
    NewEngagedViewers INT,
    ReturningEngagedViewers INT,
    PrimeSubs INT,
    TotalPaidSubs INT,
    Tier1Subs INT,
    Tier2Subs INT,
    Tier3Subs INT,
    TotalGiftedSubs INT,
    GiftedTier1Subs INT,
    GiftedTier2Subs INT,
    GiftedTier3Subs INT,
    TotalMultiMonthGiftedSubs INT,
    MultiMonthGiftedTier1Subs INT,
    MultiMonthGiftedTier2Subs INT,
    MultiMonthGiftedTier3Subs INT
);
